import type { Assignee, Project, Task } from "@/lib/types";

export const assignees: Assignee[] = [
  { id: "user-1", name: "Ayşe Yılmaz", initials: "AY" },
  { id: "user-2", name: "Mehmet Demir", initials: "MD" },
  { id: "user-3", name: "Zeynep Kaya", initials: "ZK" },
];

export const projects: Project[] = [
  {
    id: "project-1",
    name: "TaskFlow MVP",
    description: "Şirket içi görev ve proje takip uygulamasının ilk sürümü",
    progress: 48,
    dueDate: "2026-09-28",
    memberCount: 3,
  },
];

export const tasks: Task[] = [
  {
    id: "task-1",
    code: "TF-101",
    title: "Benzer ürünleri ve ihtiyaçları araştır",
    description:
      "Jira, Asana, Linear ve OpenProject özelliklerini karşılaştır.",
    project: "TaskFlow MVP",
    status: "done",
    priority: "high",
    assignee: assignees[0],
    startDate: "2026-09-11",
    dueDate: "2026-09-12",
    progress: 100,
    tags: ["Araştırma"],
    dependencyIds: [],
  },
  {
    id: "task-2",
    code: "TF-102",
    title: "Teknoloji yığınını belirle",
    description:
      "Next.js, Supabase ve kullanılacak arayüz kütüphanelerini seç.",
    project: "TaskFlow MVP",
    status: "done",
    priority: "high",
    assignee: assignees[0],
    startDate: "2026-09-12",
    dueDate: "2026-09-13",
    progress: 100,
    tags: ["Planlama"],
    dependencyIds: ["task-1"],
  },
  {
    id: "task-3",
    code: "TF-103",
    title: "Uygulama iskeleti ve menüyü hazırla",
    description: "Ortak sayfa düzeni ile temel navigasyonu oluştur.",
    project: "TaskFlow MVP",
    status: "done",
    priority: "medium",
    assignee: assignees[1],
    startDate: "2026-09-13",
    dueDate: "2026-09-15",
    progress: 100,
    tags: ["Frontend"],
    dependencyIds: ["task-2"],
  },
  {
    id: "task-4",
    code: "TF-104",
    title: "Overview ekranını oluştur",
    description: "Görev sayılarını ve proje ilerlemesini tek ekranda göster.",
    project: "TaskFlow MVP",
    status: "review",
    priority: "medium",
    assignee: assignees[1],
    startDate: "2026-09-15",
    dueDate: "2026-09-17",
    progress: 85,
    tags: ["Frontend", "Raporlama"],
    dependencyIds: ["task-3"],
  },
  {
    id: "task-5",
    code: "TF-105",
    title: "Kanban sürükle-bırak prototipi",
    description: "Kartların durum sütunları arasında taşınmasını sağla.",
    project: "TaskFlow MVP",
    status: "in_progress",
    priority: "high",
    assignee: assignees[0],
    startDate: "2026-09-16",
    dueDate: "2026-09-19",
    progress: 65,
    tags: ["Frontend", "Kanban"],
    dependencyIds: ["task-3"],
  },
  {
    id: "task-6",
    code: "TF-106",
    title: "Talep formuna doğrulama ekle",
    description: "Zod ile gerekli alanları ve tarih kurallarını kontrol et.",
    project: "TaskFlow MVP",
    status: "in_progress",
    priority: "medium",
    assignee: assignees[2],
    startDate: "2026-09-16",
    dueDate: "2026-09-20",
    progress: 50,
    tags: ["Form", "Zod"],
    dependencyIds: ["task-3"],
  },
  {
    id: "task-7",
    code: "TF-107",
    title: "Supabase tablolarını oluştur",
    description:
      "Projeler, üyeler, görevler ve yorumlar için SQL şemasını uygula.",
    project: "TaskFlow MVP",
    status: "todo",
    priority: "high",
    assignee: assignees[0],
    startDate: "2026-09-18",
    dueDate: "2026-09-21",
    progress: 0,
    tags: ["Supabase", "Database"],
    dependencyIds: ["task-2"],
  },
  {
    id: "task-8",
    code: "TF-108",
    title: "Giriş ve yetkilendirmeyi bağla",
    description: "Supabase Auth ve RLS kurallarını uygulamaya bağla.",
    project: "TaskFlow MVP",
    status: "todo",
    priority: "high",
    assignee: assignees[1],
    startDate: "2026-09-21",
    dueDate: "2026-09-24",
    progress: 0,
    tags: ["Auth", "RLS"],
    dependencyIds: ["task-7"],
  },
  {
    id: "task-9",
    code: "TF-109",
    title: "Gerçek veriyi ekranlara bağla",
    description: "Mock verileri Supabase sorguları ile değiştir.",
    project: "TaskFlow MVP",
    status: "todo",
    priority: "high",
    assignee: assignees[2],
    startDate: "2026-09-23",
    dueDate: "2026-09-26",
    progress: 0,
    tags: ["Supabase", "API"],
    dependencyIds: ["task-7", "task-8"],
  },
  {
    id: "task-10",
    code: "TF-110",
    title: "Test ve demo hazırlığı",
    description: "Temel kullanıcı akışlarını test edip sunum verisini düzenle.",
    project: "TaskFlow MVP",
    status: "todo",
    priority: "medium",
    assignee: null,
    startDate: "2026-09-26",
    dueDate: "2026-09-28",
    progress: 0,
    tags: ["Test"],
    dependencyIds: ["task-9"],
  },
];
